version: '3'
services:
  tomcat_foolish:
    build: .
    container_name: tomcat_9_jdk8_foolish
    ports:
      - "8080:8080"
    volumes:
      - ./webapps:/usr/local/tomcat/webapps
      - ./logs:/usr/local/tomcat/logs:rw
